import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { BackgroundTop, BodyController, Content, ContentContainer } from "@/Components/Body";
import Profil from "./Components/Profil";
import { Menu, Menus } from "@/Components/Body";
import { useState } from "react";
import About from "./Components/About";
import Skills from "./Components/Skills";
import ProjectWork from "./Components/ProjectWork";
import Experience from "./Components/Experience";
import Contact from "./Components/Contact";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const menu = [
  "About",
  "Skills",
  "Projects & Works",
  "Experience",
  "Contact",
  "Learning"
]
export default function Home() {
  const [menuActive, setMenuActive] = useState("About");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet" />
      </Head>
      <BodyController>
        <BackgroundTop />
        <ContentContainer>
          <Content>
            <Profil />
            <Menus>
              {
                menu?.map((m, i) => (
                  <Menu key={i} className={menuActive === m ? "active" : ""} onClick={() => setMenuActive(m)}>
                    {m}
                  </Menu>
                ))
              }
            </Menus>
            {
              menuActive === "About" ?
                <About /> :
                menuActive === "Skills" ?
                  <Skills /> :
                  menuActive === "Projects & Works" ?
                    <ProjectWork /> :
                    menuActive === "Experience" ?
                      <Experience /> :
                      menuActive === "Contact" ?
                        <Contact /> : ""
            }
          </Content>
        </ContentContainer>
      </BodyController>
    </>
  );
}
